1) import java.io.File;
   import java.io.FileNotFoundException;
   import java.util.Scanner;

    public class FileHandlingExample {
    public static void main(String[] args) {
        try {
            File file = new File("example.txt");
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                System.out.println(scanner.nextLine());
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("Error: File not found");
        }
    }
}

2) public class ArithmeticExceptionExample {
    public static void main(String[] args) {
        try {
            int result = 10 / 0;
            System.out.println("Result: " + result);
        } catch (ArithmeticException e) {
            System.out.println("Error: Division by zero is not allowed");
        }
    }
}

3) public class ArrayIndexOutOfBoundExample {
    public static void main(String[] args) {
        
        int[] numbers = {1, 2, 3, 4, 5};

        try {
           
            System.out.println(numbers[5]);
        } catch (ArrayIndexOutOfBoundsException e) {
            
            System.out.println("Array index is out of bounds: " + e.getMessage());
        }

       
        System.out.println("Program continues to run after handling the exception.");
    }
}


